### ISSUE TITLE
ModuleNotFoundError: No module named 'config.items'

### ISSUE THREAD

**Issue by johnsamuelwrites** [dpriskorn/ItemSubjector#49]
On checking the latest version and 0.3-alpha2, I am getting the following error:
```
Traceback (most recent call last):
  File "itemsubjector.py", line 3, in <module>
    import src
  File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/tmp/ItemSubjector-0.3-alpha2/src/__init__.py", line 11, in <module>
    from src.helpers.console import (
  File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/tmp/ItemSubjector-0.3-alpha2/src/helpers/console.py", line 11, in <module>
    from src.models.batch_job import BatchJob
  File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/tmp/ItemSubjector-0.3-alpha2/src/models/batch_job.py", line 3, in <module>
    from src.models.items import Items
  File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/tmp/ItemSubjector-0.3-alpha2/src/models/items/__init__.py", line 10, in <module>
    from src.models.wikimedia.wikidata.sparql_item import SparqlItem
  File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/tmp/ItemSubjector-0.3-alpha2/src/models/wikimedia/wikidata/sparql_item.py", line 4, in <module>
    import config.items
ModuleNotFoundError: No module named 'config.items'
```

**Comment by johnsamuelwrites** [comment]
I tried to solve the problem by adding `__init__.py` in the config folder.
But then I get the following error:

```
 File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/src/models/wikimedia/wikidata/entity.py", line 12, in <module>
    wbi_config.config["USER_AGENT"] = config.user_agent
AttributeError: module 'config' has no attribute 'user_agent'
```

**Comment by dpriskorn** [comment]
I now renamed config.example.py -> __init__.example.py. 
My config file on k8s looks like this and it works.
Try pulling again and copy config/__init__.example.py -> config/__init__.py, add credentials and run 
```
import logging
import tempfile

# Rename this file to __init__.py

# Add your botpassword and login here:

username = ""
password = ""

# Settings
automatically_approve_jobs_with_less_than_fifty_matches = False
loglevel = logging.WARNING
wiki_user = "User:Username"  # Change this to your username
wd_prefix = "http://www.wikidata.org/entity/"
endpoint = "https://query.wikidata.org/sparql"
user_agent = f"ItemSubjector (https://github.com/dpriskorn/ItemSubjector), {wiki_user}"
tool_url = "https://github.com/dpriskorn/ItemSubjector"
tool_wikipage = "Wikidata:Tools/ItemSubjector"
login_instance = None
# This should work for all platforms except kubernetes
job_pickle_file_path = f"{tempfile.gettempdir()}/pickle.dat"
# job_pickle_file_path = "~/pickle.dat"  # works on kubernetes

```

**Comment by johnsamuelwrites** [comment]
It's still not working and I get the following error

```
Traceback (most recent call last):
  File "itemsubjector.py", line 8, in <module>
    itemsubjector.run()
  File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/t2/ItemSubjector/src/__init__.py", line 174, in run
    process_user_supplied_qids_into_batch_jobs(args=args, task=task)
  File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/t2/ItemSubjector/src/helpers/jobs.py", line 126, in process_user_supplied_qids_into_batch_jobs
    job = process_qid_into_job(qid=qid, task=task, args=args)
  File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/t2/ItemSubjector/src/helpers/jobs.py", line 62, in process_qid_into_job
    suggestion.extract_search_strings()
  File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/t2/ItemSubjector/src/models/suggestion.py", line 174, in extract_search_strings
    elif alias in config.list_of_allowed_aliases:
AttributeError: module 'config' has no attribute 'list_of_allowed_aliases'
```

**Comment by dpriskorn** [comment]
> It's still not working and I get the following error
> 
> 
> 
> ```
> 
> Traceback (most recent call last):
> 
>   File "itemsubjector.py", line 8, in <module>
> 
>     itemsubjector.run()
> 
>   File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/t2/ItemSubjector/src/__init__.py", line 174, in run
> 
>     process_user_supplied_qids_into_batch_jobs(args=args, task=task)
> 
>   File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/t2/ItemSubjector/src/helpers/jobs.py", line 126, in process_user_supplied_qids_into_batch_jobs
> 
>     job = process_qid_into_job(qid=qid, task=task, args=args)
> 
>   File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/t2/ItemSubjector/src/helpers/jobs.py", line 62, in process_qid_into_job
> 
>     suggestion.extract_search_strings()
> 
>   File "/mnt/nfs/labstore-secondary-tools-project/itemsubjector-jsamwrites/itemsubjector/t2/ItemSubjector/src/models/suggestion.py", line 174, in extract_search_strings
> 
>     elif alias in config.list_of_allowed_aliases:
> 
> AttributeError: module 'config' has no attribute 'list_of_allowed_aliases'
> 
> ```

#53

**Comment by dpriskorn** [comment]
Should be fixed now on master. Please try again.

**Comment by dpriskorn** [comment]
I tested and fixed some more bugs and updated to the latest WBI pre-release and released a new alpha version that should work https://github.com/dpriskorn/ItemSubjector/releases
Closing this, please reopen if the latest release does not work for you.
