### ISSUE TITLE
Error in PAWS on v0.3.2 when doing single subject

### ISSUE THREAD

**Issue by Ainali** [dpriskorn/ItemSubjector#70]
After installing in PAWS I ran this command:

`poetry run python itemsubjector.py -a Q40858`

 I then selected 2 to work on Riksdagen documents. This caused this screen: 

```
Working on naturgas, see http://www.wikidata.org/entity/Q40858
Got a total of 78 items
Please keep an eye on the lag of the WDQS cluster here and avoid working if it is over a few minutes.
https://grafana.wikimedia.org/d/000000489/wikidata-query-service?orgId=1&viewPanel=8&from=now-30m&to=now&refresh=1d You can see if any lagging servers are pooled here
https://config-master.wikimedia.org/pybal/eqiad/wdqs
If any enabled servers are lagging more than 5-10 minutes you can search phabricator for open tickets to see if the team is on it.
If you don't find any feel free to create a new ticket like this:
https://phabricator.wikimedia.org/T291621
Running 1 job(s) with a total of 1 items non-interactively now. You can take a coffee break and lean back :)
Traceback (most recent call last):
  File "/home/paws/.itemsubjector/itemsubjector.py", line 8, in <module>
    itemsubjector.run()
  File "/home/paws/.itemsubjector/src/__init__.py", line 164, in run
    handle_job_preparation_or_run_directly_if_any_jobs(
  File "/home/paws/.itemsubjector/src/helpers/jobs.py", line 154, in handle_job_preparation_or_run_directly_if_any_jobs
    batchjobs.run_jobs()
  File "/home/paws/.itemsubjector/src/models/batch_jobs.py", line 45, in run_jobs
    job.suggestion.add_to_items(
  File "/home/paws/.itemsubjector/src/models/suggestion.py", line 111, in add_to_items
    f"to {clean_rich_formatting(target_item.label)}"
  File "/home/paws/.itemsubjector/src/helpers/cleaning.py", line 24, in clean_rich_formatting
    return label.replace("[/", "['/")
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by dpriskorn** [comment]
- [] add test for label being none

**Comment by dpriskorn** [comment]
Solving this issue was not easy because the code is not so easy to test currently. 

I started a rewrite of the classes involved to make the code easier to test and debug.

**Comment by dpriskorn** [comment]
It should be fixed if you check out this branch https://github.com/dpriskorn/ItemSubjector/pull/71
