### ISSUE TITLE
PAWS v0.3.3: no_alias_for_scholarly_items error

### ISSUE THREAD

**Issue by Ainali** [dpriskorn/ItemSubjector#75]
I get this error in PAWS on v0.3.3 when doing single subject:

```
Picking a random main subject
Working on naturgas
Do you want to continue? [Y/Enter/n]: 
Traceback (most recent call last):
  File "/home/paws/.itemsubjector/itemsubjector.py", line 8, in <module>
    itemsubjector.run()
  File "/home/paws/.itemsubjector/src/__init__.py", line 79, in run
    main_subjects.get_validated_main_subjects_as_jobs()
  File "/home/paws/.itemsubjector/src/models/main_subjects.py", line 108, in get_validated_main_subjects_as_jobs
    job = main_subject_item.fetch_items_and_get_job_if_confirmed()
  File "/home/paws/.itemsubjector/src/models/wikimedia/wikidata/item/main_subject.py", line 240, in fetch_items_and_get_job_if_confirmed
    return self.__fetch_and_parse__()
  File "/home/paws/.itemsubjector/src/models/wikimedia/wikidata/item/main_subject.py", line 250, in __fetch_and_parse__
    self.__prepare_before_fetching_items__()
  File "/home/paws/.itemsubjector/src/models/wikimedia/wikidata/item/main_subject.py", line 188, in __prepare_before_fetching_items__
    self.__extract_search_strings__()
  File "/home/paws/.itemsubjector/src/models/wikimedia/wikidata/item/main_subject.py", line 141, in __extract_search_strings__
    elif self.id in config.no_alias_for_scholarly_items:
AttributeError: module 'config' has no attribute 'no_alias_for_scholarly_items'
```

My command was `poetry run python itemsubjector.py -a Q40858`

**Comment by dpriskorn** [comment]
I simplified the config and moved this and a few other variables. 
They are in the sample as seen here
![image](https://user-images.githubusercontent.com/68460690/194694030-e8825920-7497-4f9e-b255-ba8dcf9b846e.png)

**Comment by Ainali** [comment]
I updated my config.py to include this, but I still get the error in the top.

**Comment by dpriskorn** [comment]
I don't understand. I only see one error. Please open a new issue for each error you get.

**Comment by Ainali** [comment]
I meant that I get _the same_ error even after updating my config.py with the example.

**Comment by dpriskorn** [comment]
I changed the location of the config file. Please send me the output of 

$ tree .

In the folder of the tool. 
I'm guessing you still have a directory called config.

**Comment by Ainali** [comment]
That does not work:

```
@PAWS:~/.itemsubjector$ tree .
bash: tree: command not found
```

**Comment by dpriskorn** [comment]
Oh. Ok then

$ ls -l

**Comment by Ainali** [comment]
```
@PAWS:~/.itemsubjector$ ls -l
total 220
drwxr-sr-x 3 tools.paws tools.paws  4096 Oct  6 09:14 config
-rw-r--r-- 1 tools.paws tools.paws  1288 Oct  6 09:14 config.example.py
-rw-r--r-- 1 tools.paws tools.paws  1324 Oct  8 08:11 config.py
-rw-r--r-- 1 tools.paws tools.paws   295 Oct  1 19:41 create_kubernettes_job_and_watch_the_log.sh
drwxr-sr-x 2 tools.paws tools.paws  4096 Nov 18  2021 data
drwxr-sr-x 2 tools.paws tools.paws  4096 Oct  6 09:14 diagrams
drwxr-sr-x 3 tools.paws tools.paws  4096 Nov 18  2021 helpers
-rw-r--r-- 1 tools.paws tools.paws   156 Oct  1 19:41 itemsubjector.py
-rw-r--r-- 1 tools.paws tools.paws  2772 Oct  2 07:50 Kubernetes_HOWTO.md
-rw-r--r-- 1 tools.paws tools.paws 35149 Sep 17  2021 LICENSE
drwxr-sr-x 3 tools.paws tools.paws  4096 Nov 18  2021 models
-rw-r--r-- 1 tools.paws tools.paws 88294 Oct  6 09:14 poetry.lock
drwxr-sr-x 2 tools.paws tools.paws  4096 Jul 27 18:23 __pycache__
-rw-r--r-- 1 tools.paws tools.paws  1545 Oct  6 09:14 pyproject.toml
-rw-r--r-- 1 tools.paws tools.paws 12211 Oct  6 09:14 README.md
-rw-r--r-- 1 tools.paws tools.paws   347 Oct  6 09:14 RELEASE.md
-rw-r--r-- 1 tools.paws tools.paws 17630 Oct  2 07:50 requirements.txt
-rw-r--r-- 1 tools.paws tools.paws    78 Nov 18  2021 setup_environment.sh
drwxr-sr-x 5 tools.paws tools.paws  4096 Oct  6 09:14 src
drwxr-sr-x 2 tools.paws tools.paws  4096 Oct  6 09:14 tests
```

**Comment by dpriskorn** [comment]
Copy over your credentials to config.py. Then Delete the config directory with

$ rm -r config

**Comment by Ainali** [comment]
That did indeed solve it, thanks for the patience!
